packages:
  - 'mermaid-diagram-pan-zoom'
  - 'docusaurus-plugin-mermaid-pan-zoom'
  - 'examples'
allowBuilds:
  core-js: false
overrides:
  mermaid-diagram-pan-zoom: 'workspace:*'
  serialize-javascript: '>=7.0.3'
